// Generated by CoffeeScript 1.4.0
var casper;

casper = require('casper').create();

casper.start('http://lifephoto.herokuapp.com', function() {
  this.capture("top.png");
  this.test.assertTitle('LifePhotos');
  this.test.assertTextExists('Wellcome', 'Wellcome message exists');
  return this.click("a[rel=facebook_login]");
});

casper.then(function() {
  this.capture("login.png");
  return this.test.assertTitle('Facebook', ' title is the one expected');
});

casper.run(function() {
  this.test.done(3);
  return this.test.renderResults(true);
});
