// Generated by CoffeeScript 1.4.0
var casper, getLinks, links;

getLinks = function() {
  var links;
  links = document.querySelectorAll("h3.r a");
  return Array.prototype.map.call(links, function(e) {
    return e.getAttribute("href");
  });
};

links = [];

casper = require('casper').create();

casper.start("http://www.google.co.jp/", function() {
  return this.fill("form[action='/search']", {
    q: "casperjs"
  }, true);
});

casper.then(function() {
  return links = this.evaluate(getLinks);
});

casper.run(function() {
  this.echo(links.length + "links found:");
  return this.echo("-" + links.join("\n-")).exit();
});
