#
# This file configures the Treasure Data, Hadoop-based cloud data warehouse.
# For more information, visit http://www.treasure-data.com/.
#
production:
  # Treasure Data API Key
  # TREASURE_DATA_API_KEY is automatically defined when you add treasure-data
  # heroku addon.
  apikey: "3184/6e44b9203a625d1fa8fa7d4477868c7ff46331e4"

  # Database name
  # Set this to be the name of your database as you'd like it show up in
  # `heroku td dbs` command.
  database: lifephoto
  #database: production

  # Debug Mode
  # Less verbose for production environment.
  debug_mode: false

development:
  # Treasure Data API Key
  # `heroku td apikey:show` will retrieve the apikey through Heroku API.
  apikey: "3184/6e44b9203a625d1fa8fa7d4477868c7ff46331e4"

  # Database name
  # Set this to be the name of your database as you'd like it show up in
  # `heroku td dbs` command.
  database: dev_lifephoto
  #database: development

  # Debug Mode
  # More verbose tracing is enabled for development environment.
  debug_mode: true

# For test environment, logging to Treasure Data is disabled by default.
test:
