// Generated by CoffeeScript 1.4.0

App.controller('EventsCtrl', [
  '$scope', function($scope) {
    return $scope.message = "Angular Rocks!";
  }
]);

App.controller('EventsCtrl', [
  '$scope', 'Events', function($scope, Events) {
    return $scope.events = Events.query();
  }
]);
